### ISSUE TITLE
[ISSUE]Appearing pop-up of the packagemanager on focus of editor

### ISSUE THREAD

**Issue by robvld** [VeriorPies/ParrelSync#34] opened 2021-03-08 13:51 UTC
**Describe the bug**
A pop-up of the package manager appears saying Trying to resolve packages, when focusing between the editors
Happens always

**To Reproduce**
1. Create new project
2. Create new clone
3. Focus between original and clone
4. Popup appears on focus saying Resolving packages, delaying the project

**Expected behavior**
Nothing should appear

**Enviroment (please complete the following information):**
 - Unity Editor Version: [e.g. Windows 2019.4.21f1]
 - ParrelSync Version [e.g. 1.4.2]

**Additional context**
mkLink gives the same error

**Comment by TheKrane** [comment] 2021-03-09 13:29
This started happening to me too after installing the UIToolkit and UIEditor packages on Unity 2020.2.7f1.
Not a deal-breaking bug, but very annoying.

**Comment by 314pies** [comment] 2021-03-10 16:31
Hi, thanks for reporting.
This is a known issue, please refer to the "[Why is Unity keeps Resolving packages when switching between clone and original?](https://github.com/VeriorPies/ParrelSync/wiki/Troubleshooting-&-FAQs)" for the temporary workaround.

**Comment by 314pies** [comment] 2021-04-27 22:52
Duplicate of #23

**Closed by 314pies** 2021-04-27 22:52 UTC
Labels: bug
