### ISSUE TITLE
[BUG] ParrelSync don't work properly with Mixed Reality Tool

### ISSUE THREAD

**Issue by Haruwolf** [VeriorPies/ParrelSync#66] opened 2021-11-23 13:31 UTC
**Describe the bug**
Trying to clone a project with Unity Mixed Reality Tool, with Standard Tools, OpenXR plugin don't clone and get stuck on "hold on".

**To Reproduce**
1. Create a new project on Unity
2. Use MRTK, install Standard Assets and OpenXR plugin
3. Install ParrelSync via git
4. Try to clone a project

**Expected behavior**
The project don't clone get stuck on importing assets window.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/44352381/143032777-b8a1c5b5-2387-4333-bbf0-adce725d0e2b.png)

**Enviroment (please complete the following information):**
 - Unity Editor Version: 2020.3.20f1
 - ParrelSync Version: (For Example: 1.5.0)
 - OS Version: Windows 10 Home Edition

**Comment by 314pies** [comment] 2022-02-04 05:54
Duplicate of #55

**Closed by 314pies** 2022-02-04 05:54 UTC
Labels: bug
