### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Regenyi** [VeriorPies/ParrelSync#21] opened 2020-12-04 12:09 UTC
**Describe the feature you'd like**
Linux version :)

**Comment by 314pies** [comment] 2020-12-05 16:07
The new release now have Linux support :)
https://github.com/VeriorPies/ParrelSync/releases/tag/1.4.2

**Comment by 314pies** [comment] 2020-12-05 16:08
Duplicate of #12

**Closed by 314pies** 2020-12-05 16:08 UTC
