### ISSUE TITLE
[Feature Request] Packages folder sync

### ISSUE THREAD

**Issue by Phantomxm2021** [VeriorPies/ParrelSync#58] opened 2021-10-04 00:35 UTC
**Describe the feature you'd like**
Thank you, the Parrel Sync is a amzing plugin for mupltiplayer dev. 
But at this time, The parrel sync do not support sync of the packages folder.

**Comment by 314pies** [comment] 2022-02-04 06:03
Duplicate of #57

**Closed by 314pies** 2022-02-04 06:03 UTC
