### ISSUE TITLE
Looks like ParrelSync is affecting the Package Manager

### ISSUE THREAD

**Issue by CK85** [VeriorPies/ParrelSync#24] opened 2021-01-13 10:15 UTC
Hi,
at first, thanks for this great tool! I just noticed that, when I switch between the original and the cloned unity editors the Package Manager starts "Resolving packages". It takes only a few seconds but it is a bit annoying when you constantly switch between the windows. This doesn't seem to happen, when I use a different unity instance and not the cloned instance. I'm using Unity 2020.2.

Best regards,
Chris

**Comment by 314pies** [comment] 2021-01-13 10:18
Hi CK85,
I think this may help https://github.com/VeriorPies/ParrelSync/issues/23#issuecomment-757777213.

Will take a deeper look later.

**Comment by 314pies** [comment] 2021-04-27 22:35
Duplicate of #23

**Closed by 314pies** 2021-04-27 22:35 UTC
