### ISSUE TITLE
[BUG] Cannot create clone - Packages 'root' argument directory?

### ISSUE THREAD

**Issue by TheYellowArchitect** [VeriorPies/ParrelSync#29] opened 2021-02-05 14:59 UTC
**Describe the bug**
I pressed "Open in New Editor" and I got the error:
>Failed to resolve packages: `root` argument is not a directory. No packages loaded.
A re-import of the project may be required to fix the issue or a manual modification of C:/Users/unity/Desktop/Unity/Double Damnation/Co-Op Prototype/46e/Co-Op Prototype_clone_0/Packages/manifest.json file.

If I press Continue, and open the project, I get:
>The type `UnityEngine.MonoBehaviour' has been forwarded to an assembly that is not referenced. Consider adding a reference to assembly `UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
error CS1070: Assets/Bearded Man Studios Inc/Generated/NetworkManager.cs(7,40)

**To Reproduce**
1. Import Forge Networking Remastered
2. Open Unity (2018.1.1f1?)
3. Clear all up all legacy issues https://github.com/VeriorPies/ParrelSync/issues/27
4. Create New Clone
5. Clone Created Succesfully
6. Open New Editor
7. Error
![14](https://user-images.githubusercontent.com/25630803/107050823-8cc30d00-6780-11eb-9b3c-4f2ed73ad1f7.PNG)
8. Continue anyway to see if it works
 ![14](https://user-images.githubusercontent.com/25630803/107049976-95ffaa00-677f-11eb-9793-63020308e398.PNG)

**Expected behavior**
Given it was suggested in the Forge Networking discord, I expected it to work. To simply create a new Unity instance.

**Enviroment**
 - Unity Editor Version: Windows 2018.1.f1
 - ParrelSync Version 1.4.1
 
 **Additional Information**
This is the packages folder, the clones get from the original project
![14](https://user-images.githubusercontent.com/25630803/107051007-c6941380-6780-11eb-9ae5-ce72122d77cd.PNG)
![14](https://user-images.githubusercontent.com/25630803/107050978-bd0aab80-6780-11eb-8fb1-66d58d547bbe.PNG)
![14](https://user-images.githubusercontent.com/25630803/107052530-a06f7300-6782-11eb-9b61-0251394d91e0.PNG)

**Comment by TheYellowArchitect** [comment] 2021-02-05 17:43
https://github.com/VeriorPies/ParrelSync/issues/23
https://github.com/VeriorPies/ParrelSync/issues/24

It turns out this is the same issue. I did what @tarss said (delete package of the clone and copy-paste original there), and it works.

It is a hack, so I ask, whoever maintains this, should I close this issue? My issue is solved, after all hahaha

**Comment by 314pies** [comment] 2021-04-27 22:35
Duplicate of #23

**Closed by 314pies** 2021-04-27 22:35 UTC
Labels: bug
